# Site
name: "Andrew's Blog"
title: "Andrew's Blog"
description: "Stuff I don't want to forget"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  andrew:
    name: Andrew
    display_name: Andrew
    gravatar: 49fce3d087f13323929e3070c724ae6d
    email: andrew@aguest.me
    web: https://www.aguest.me
    description: "I'm just a guy with a degree in Computer Security, working as a Linux System Administrator with a love for programming."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
